apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      name: backend
  template:
    metadata:
      labels:
        name: backend
    spec:
      hostNetwork: true
      containers:
      - name: backend
        image: ibraheemsar/backend
        ports:
        - containerPort: 5000
      hostname: backend
